# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: BDD tests tag - FIRST

on:
  pull_request:
    branches: [ develop ]
env:
      NODE_ENV: development
      ARTIFACTS_DIR: ./artifacts
      CUCUMBER_ARTIFACTS_DIR: ./artifacts/cucumber
jobs:
  test-unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [9.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: mkdir -p $ARTIFACTS_DIR
      - run: mkdir -p $CUCUMBER_ARTIFACTS_DIR
      - run: sudo ./setup_arangodb.sh
      - run: cp .origintrail_noderc.travis .origintrail_noderc
      - run: npm run lint
      - run: npm run test:unit > $ARTIFACTS_DIR/mocha-logs.log;
      - name: install s3cmd
        if: ${{ always() }}
        run: apt-get s3cmd
      - name: upload to AWS bucket
        if: ${{ always() }}
        run: s3cmd --acl-public --access_key=${{secrets.AWS_ACCESS_KEY}} --secret_key=${{secrets.AWS_ACCESS_SECRET}} put --recursive $ARTIFACTS_DIR/* s3://{{secrets.AWS_BUCKET_NAME}}/test/test1/123456/
