# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Lint and Unit tests

on:
  pull_request:
    branches: [ develop ]
env:
  NODE_ENV: development
  ARTIFACTS_DIR: artifacts
  CUCUMBER_ARTIFACTS_DIR: artifacts/cucumber
jobs:
  test-unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [9.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    environment: Testing
    steps:
      - run: mkdir -p $ARTIFACTS_DIR
      - run: sudo chmod -R 777 $ARTIFACTS_DIR
      - run: mkdir -p $CUCUMBER_ARTIFACTS_DIR
      - run: sudo chmod -R 777 $CUCUMBER_ARTIFACTS_DIR
      - run: pwd
      - run: ls -l
      - uses: actions/checkout@v2
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
          aws-region: eu-central-1

      - name: Copy files to the test website with the AWS CLI
        run: |
          aws s3 sync artifacts s3://origintrail-travis-ci
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install

      - run: sudo ./setup_arangodb.sh
      - run: cp .origintrail_noderc.travis .origintrail_noderc
      - run: npm run lint
      - run: npm run test:unit > $ARTIFACTS_DIR/mocha-logs.log;

