# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: BDD tests tag - FIRST

on:
  pull_request:
    branches: [ develop ]
env:
  NODE_ENV: development
  ARTIFACTS_DIR: ./artifacts
  CUCUMBER_ARTIFACTS_DIR: ./artifacts/cucumber
jobs:
  test-unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [9.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - uses: shallwefootball/s3-upload-action@master
        name: Upload S3
        if: ${{ always() }}
        id: S3
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.AWS_ACCESS_SECRET}}
          aws_bucket: ${{ secrets.AWS_BUCKET_NAME }}
          source_dir: $ARTIFACTS_DIR
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: mkdir -p $ARTIFACTS_DIR
      - run: mkdir -p $CUCUMBER_ARTIFACTS_DIR
      - run: sudo ./setup_arangodb.sh
      - run: cp .origintrail_noderc.travis .origintrail_noderc
      - run: npm run lint
      - run: npm run test:unit > $ARTIFACTS_DIR/mocha-logs.log;

