# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: BDD tests tag - FIRST

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      NODE_ENV: development
      ARTIFACTS_DIR: $TRAVIS_BUILD_DIR/artifacts
      CUCUMBER_ARTIFACTS_DIR: $ARTIFACTS_DIR/cucumber      
    strategy:
      matrix:
        node-version: [9.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: mkdir -p $ARTIFACTS_DIR
    - run: mkdir -p $CUCUMBER_ARTIFACTS_DIR
    - run: sudo ./setup_arangodb.sh
    - run: cp .origintrail_noderc.travis .origintrail_noderc
    - run: npm run bootstrap
    - run: npm run test:bdd -- --tags=@first --world-parameters '{"appDataBaseDir":"$CUCUMBER_ARTIFACTS_DIR","keepFailedArtifacts":true}';
