name: CHECK-lint

#todo this test should be execute when opening PR to prerelease/release branches
on: [pull_request]
env:
  NODE_ENV: test
  ARTIFACTS_DIR: artifacts
  CUCUMBER_ARTIFACTS_DIR: artifacts/cucumber
jobs:
  check-lint:
    #todo think about locking the version - version should be the same as the one in official documentation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: mkdir -p $ARTIFACTS_DIR
      - run: cp tools/local-network-setup/.origintrail_noderc_template.json .origintrail_noderc
      - run: sudo chmod -R 777 $ARTIFACTS_DIR
      - run: mkdir -p $CUCUMBER_ARTIFACTS_DIR
      - run: sudo chmod -R 777 $CUCUMBER_ARTIFACTS_DIR
      - run: npm run lint;
      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: my-artifact
          path: /home/runner/work/ot-node/ot-node/artifacts
