name: checks

on:
  pull_request:
    branches:
      - v6/develop

concurrency:
  group: checks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up environment
        uses: ./.github/actions/setup

      - name: Run linter
        run: npm run lint

  unit-tests:
    runs-on: ubuntu-latest
    services:
      graphdb:
        image: khaller/graphdb-free:latest
        ports:
          - 7200:7200
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up environment
        uses: ./.github/actions/setup

      - name: Run unit tests
        run: npm run test:unit

  bdd-tests:
    runs-on: ubuntu-latest
    services:
        mysql:
          image: mysql:5.7
          env:
            MYSQL_DATABASE: operationaldb
            MYSQL_USER: node
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
          ports:
            - 3306:3306
          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up environment
        uses: ./.github/actions/setup

      - name: Run Blazegraph
        run: /usr/bin/java -Djava.awt.headless=true -jar blazegraph.jar

      - name: Run BDD tests
        run: npm run test:bdd

      
