name: TEST-bdd

#todo this test should be execute when opening PR to prerelease/release branches
on: [pull_request]
env:
  NODE_ENV: test
  ARTIFACTS_DIR: artifacts
  CUCUMBER_ARTIFACTS_DIR: artifacts/cucumber
  REPOSITORY_PASSWORD: password
jobs:

  test-bdd:
    #todo think about locking the version - version should be the same as the one in official documentation
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: operationaldb
          MYSQL_USER: node
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      blazegraph:
        image: lyrasis/blazegraph:2.1.5
        ports:
          - 9999:9999
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: docker ps
      - run: curl http://blazegraph:9999
      - run: npm install
      - run: mkdir -p $ARTIFACTS_DIR
      - run: sudo chmod -R 777 $ARTIFACTS_DIR
      - run: mkdir -p $CUCUMBER_ARTIFACTS_DIR
      - run: sudo chmod -R 777 $CUCUMBER_ARTIFACTS_DIR
      - run: npm explore dkg-evm-module -- npm run compile;
      - run: npm run test:bdd;
      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: my-artifact
          path: /home/runner/work/ot-node/ot-node/artifacts
