name: TEST-truffle

on: [pull_request]
env:
  NODE_ENV: development
  ARTIFACTS_DIR: artifacts
  CUCUMBER_ARTIFACTS_DIR: artifacts/cucumber
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [9.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: mkdir -p $ARTIFACTS_DIR
      - run: sudo chmod -R 777 $ARTIFACTS_DIR
      - run: mkdir -p $CUCUMBER_ARTIFACTS_DIR
      - run: sudo chmod -R 777 $CUCUMBER_ARTIFACTS_DIR
      - run: sudo ./setup_arangodb.sh
      - run: cp .origintrail_noderc.travis .origintrail_noderc
      - run: npm run ganache > $ARTIFACTS_DIR/run-ganache1.log & npm run truffle:test > $ARTIFACTS_DIR/truffle-test.log;
      - run: npm run ganache > $ARTIFACTS_DIR/run-ganache2.log & npm run truffle:deploy:ganache > $ARTIFACTS_DIR/truffle-migrate.log;
      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: my-artifact
          path: /home/runner/work/ot-node/ot-node/artifacts
